### ISSUE TITLE
What is "alias lookup", and why does it take so long?

### ISSUE THREAD

**Issue by NSExceptional** [prathercc/discrub-ext#101]
I looked at the code and it looks like it's looking up usernames for each message or something? Can't those be cached to make it faster?

Edit: maybe I'm just in a really big server with a lot of users and it's doing lookups for each user, but 30k seems like a lot to me.

Regardless, I would like a way to skip this step if possible. It takes the longest and all I really want to do is download all the media in a given channel. So I guess this is a feature request

**Comment by NSExceptional** [comment]
Reaction lookup also takes a while and should be skippable

**Comment by prathercc** [comment]
I’ll add a setting to make the Alias Lookup optional 👍

What that step is, is that display names and guild names are being looked up for better readability in exported messages, but it definitely makes sense to have that be optional since not everyone may need that.

Thanks for the request, I’ll reply back here once it’s added 🤞

**Comment by prathercc** [comment]
Hey there, Version 1.11.11 will have the additional settings so that Guild Data and Alias lookups can be skipped. It should be available in the next day or so 👍
