### ISSUE TITLE
Ability to select category, to select all channels in that category

### ISSUE THREAD

**Issue by time4nothing** [prathercc/discrub-ext#110]
This program worked great for me, I will definitely donate when I have some funds! Only thing that did not meet my needs, I had to search for and select each channel individually. Would be great to just select a category, and all channels under that category would be selected (since all the channels I wanted were under a specific category).

**Comment by jirafey** [comment]
Bumping this up!

![image](https://github.com/user-attachments/assets/68a6e135-f9cc-4040-bbe8-7481157bbd26)

### EXPECTED BEHAVIOUR:

channels:
- a
- b
- bb
- bc
- bbbbb
- c
- d

FILTER: "b"

RESULTS  OF THE FILTER:

- b
- bb
- bc
- bbbbb

SELECT ALL (FROM FILTERED LIST)-> SELECT JUST THE `"b*"`
- 4 channels selected. :
- b
- bb
- bc
- bbbbb

### CURRENT BEHAVIOUR:

- a
- b
- bb
- bc
- bbbbb
- c
- d

FILTER: "b"

RESULTS  OF THE FILTER:

- b
- bb
- bc
- bbbbb


SELECT ALL: 
7 channels selected. :
- a
- b
- bb
- bc
- bbbbb
- c
- d
