### ISSUE TITLE
Reverse Filtering Before Whole Server Export is NOT Possible !!

### ISSUE THREAD

**Issue by RoroRoze** [prathercc/discrub-ext#121]
When trying to export whole server but without my Messages, I can't reverse filter or include all users except me or specific user.
as reverse filter usually show up after searching a channel but when exporting whole serve this step is passed.
so the solution could be to allow reverse filter before the channel search.

Screenshot:
![image](https://github.com/user-attachments/assets/32549bea-7463-4aa0-bb72-86f7f246cfb4)

**Comment by prathercc** [comment]
Unfortunately the Advanced Filtering is limited by what is available using Discord API, and they do not offer a way to do a reverse filter 😕.
The reverse filter is only available/possible using the Quick Filtering, since all of that logic belongs to Discrub itself.

Going to go ahead and close this issue, but please feel free to create another one if needed
