### ISSUE TITLE
Messages in forums fail to delete

### ISSUE THREAD

**Issue by PhatCJ** [prathercc/discrub-ext#53]
As the title says, messages in forums (the icon with the 2 overlaid speech bubbles ![forumicon](https://github.com/prathercc/discrub-ext/assets/87760155/2590a9b6-e4d2-45d0-aed7-deb7d32e2e2b)) fail to delete, stating that I don't have permission to modify the message, however going to affected messages and manually deleting them (outside of discrub) works just fine. 

![forumnopermission](https://github.com/prathercc/discrub-ext/assets/87760155/a5b5105d-d0a7-407c-949b-ab786d5d0513)

I *think* forums are only a thing on large(ish) community servers, as I couldn't recreate this on my private little test server (the forum option simply isn't there at all). I think this might be why this went unnoticed so far (?)

**Comment by prathercc** [comment]
Thanks for reporting this issue, I haven't had to opportunity yet to test the extension on Forum messages, but I'll try to do that soon and see if I can figure out whats going on there.

**Comment by port19x** [comment]
same for threads!

**Comment by prathercc** [comment]
Just got around to testing this out, didn't see any issue with deletes in forums (manual or via Purge) @PhatCJ, Is it possible that the messages that failed to delete were from another User? (thinking that another users messages were accidentally selected before using the delete function), I would also think that it is possible that the forum is archived (and so deletes possibly prevented, similar to archived threads), but you did mention that you were able to manually delete them outside of Discrub.

@port19x Do you know if the issue was happening on an archived thread? Currently there isn't a way to delete messages from an archived thread (atleast using Discrub), but unarchived threads should be unaffected.

**Comment by port19x** [comment]
Only saw your update now, I'll check at my earliest convenience

**Comment by prathercc** [comment]
Just checking in to see if you have had any luck with this lately?

**Comment by port19x** [comment]
Just checked, no permissions :/

**Comment by storyinstitches** [comment]
Hi, just wanted to say I am experiencing this same issue. I'm deleting another users messages, but I am server owner so I should have permissions to delete everywhere. But in threads and forums it says I do not have permissions in discrub, while I'm able to delete them manually through the discord UI.

**Comment by prathercc** [comment]
> Hi, just wanted to say I am experiencing this same issue. I'm deleting another users messages, but I am server owner so I should have permissions to delete everywhere. But in threads and forums it says I do not have permissions in discrub, while I'm able to delete them manually through the discord UI.

Hey there, just letting you know that I did finally run into this issue myself as well, I’m going to have this resolved in the next release.
I’ll update here again once it’s been fixed 👍

**Comment by prathercc** [comment]
Alright this should be resolved with PR #72
Version 1.11.1 has this fix and should be available in the next day or so, I am going to go ahead and close out this issue, but if you notice any similar problems after 1.11.1 is published, feel free to create another issue!

**Comment by port19x** [comment]
Can confirm, it works now
