### ISSUE TITLE
Messages by (user) doesn't work

### ISSUE THREAD

**Issue by Bruhstander** [prathercc/discrub-ext#55]
When in a guild, the only user showed is myself and when I have it selected in a dm it doesn't work at all and instead just searches the entire dm

**Comment by prathercc** [comment]
Hey thanks for reporting this issue! It looks like searching DM's using Advanced Filters is currently broken, trying to fix now.
And for Guild, due to API limitations, only your username will be displayed, however you can paste any Users userId and search for their messages.
A quick way to grab another Users userId is to load a few messages from them (via DM or Channel) and click their avatar, it will automatically copy their userId to your clipboard, which can then be pasted into the Messages By field.

**Comment by prathercc** [comment]
It turns out Guild was also affected by this bug, but a fix has been made in PR #57 and has also been submitted to the Chrome Webstore (Version 1.10.11).
This fix should be available to you by tomorrow once its approved.
