### ISSUE TITLE
Stalls and doesn't get anywhere, deets inside

### ISSUE THREAD

**Issue by DrizzintahL** [prathercc/discrub-ext#60]
https://gyazo.com/8b8ff4b983a68a1d99a84a3bc6644eb7

This is where it stops, left alone for quite sometime, didn't get anywhere.  This is a fresh install of Windows 10, tried on Brave & Chrome with no other extensions.  Tried lowering the search window to 3 days, and then it stalls at 50 instead.  Doesn't get past this.

**Comment by DrizzintahL** [comment]
Ack!  Disregard! It's working!  I'm sorry about that.  It takes about 3-10 minutes now (before it was super quick) but it still works!

**Comment by prathercc** [comment]
Ahh this is related to the latest User mention changes I recently made (#59), basically whats happening is that each uniquely mentioned User is being looked up in order to correctly render their usernames.
I'll see about adding some additional feedback so that you can at least see that there is something happening while waiting.
